import { defineAsyncComponent } from "vue";
import { defineView } from "../../../runtime/view/manifest";
import { invokeCoordinatePlaneMainCapability } from "./capabilities";
import { coordinatePlaneMainExamples } from "./examples";
import { coordinatePlaneMainPersistence } from "./model/persistence";
import {
  cloneCoordinatePlaneResource,
  COORDINATE_PLANE_DEFAULT_RESOURCE,
  normalizeCoordinatePlaneResource,
  openCoordinatePlaneMainView,
  readCoordinatePlaneResourceData,
  validateCoordinatePlaneResource,
} from "./model/resource";
import { buildCoordinatePlaneMainStateSummary } from "./model/summary";

const CoordinatePlaneMainView = defineAsyncComponent(() => import("./CoordinatePlaneMainView.vue"));

export {
  cloneCoordinatePlaneResource,
  COORDINATE_PLANE_DEFAULT_RESOURCE,
  normalizeCoordinatePlaneResource,
  openCoordinatePlaneMainView,
  readCoordinatePlaneResourceData,
  validateCoordinatePlaneResource,
} from "./model/resource";
export { buildCoordinatePlaneMainStateSummary } from "./model/summary";
export { coordinatePlaneMainPersistence } from "./model/persistence";
export * from "./model/types";

export const coordinatePlaneMainView = defineView({
  view_id: "plane.main",
  resource_type: "plane.scene",
  title: "Coordinate Lab",
  component: CoordinatePlaneMainView,
  state_mode: "stateful",
  default_resource: COORDINATE_PLANE_DEFAULT_RESOURCE,
  anchors: [
    { id: "plane.header", title: "Header", description: "Floating coordinate-lab title and quick state strip." },
    { id: "plane.stage", title: "Stage", description: "Full-screen JSXGraph board for coordinates, graphs, highlights, and motion." },
  ],
  capabilities: [
    {
      id: "plane.set_viewport",
      mode: "write",
      title: "Set Viewport",
      description: "Set coordinate bounds and toggle grid or axes visibility.",
      assistant_hint: "Use this early so later points, lines, and moving objects are framed correctly for narration.",
      input_schema: {
        type: "object",
        properties: {
          x_min: { type: "number" },
          x_max: { type: "number" },
          y_min: { type: "number" },
          y_max: { type: "number" },
          show_grid: { type: "boolean" },
          show_axes: { type: "boolean" },
        },
        required: ["x_min", "x_max", "y_min", "y_max"],
      },
      affected_anchors: ["plane.stage"],
      error_codes: ["invalid_view_capability_input"],
    },
    {
      id: "plane.clear_scene",
      mode: "write",
      title: "Clear Scene",
      description: "Clear all rendered objects and highlights. Optionally reset viewport too.",
      input_schema: {
        type: "object",
        properties: {
          reset_viewport: { type: "boolean" },
        },
      },
      affected_anchors: ["plane.stage"],
    },
    {
      id: "plane.add_point",
      mode: "write",
      title: "Add Point",
      description: "Add or replace one point in the coordinate plane.",
      input_schema: {
        type: "object",
        properties: {
          id: { type: "string" },
          x: { type: "number" },
          y: { type: "number" },
          label: { type: "string" },
          color: { type: "string" },
          size: { type: "number", minimum: 1, maximum: 12 },
        },
      },
      affected_anchors: ["plane.stage"],
    },
    {
      id: "plane.add_line",
      mode: "write",
      title: "Add Line",
      description: "Add either a segment or an infinite line defined by two points.",
      input_schema: {
        type: "object",
        properties: {
          id: { type: "string" },
          line_type: { type: "string", enum: ["segment", "line"] },
          x1: { type: "number" },
          y1: { type: "number" },
          x2: { type: "number" },
          y2: { type: "number" },
          label: { type: "string" },
          color: { type: "string" },
          width: { type: "number", minimum: 1, maximum: 8 },
          dashed: { type: "boolean" },
        },
        required: ["x1", "y1", "x2", "y2"],
      },
      affected_anchors: ["plane.stage"],
      error_codes: ["invalid_view_capability_input"],
    },
    {
      id: "plane.add_curve",
      mode: "write",
      title: "Add Curve",
      description: "Add a polyline-like curve by passing ordered coordinate points.",
      input_schema: {
        type: "object",
        properties: {
          id: { type: "string" },
          points: {
            type: "array",
            minItems: 2,
            items: {
              type: "object",
              properties: {
                x: { type: "number" },
                y: { type: "number" },
              },
              required: ["x", "y"],
            },
          },
          label: { type: "string" },
          color: { type: "string" },
          width: { type: "number", minimum: 1, maximum: 8 },
        },
        required: ["points"],
      },
      affected_anchors: ["plane.stage"],
      error_codes: ["invalid_view_capability_input"],
    },
    {
      id: "plane.add_circle",
      mode: "write",
      title: "Add Circle",
      description: "Add a true circle using center and radius, suitable for geometry explanation.",
      assistant_hint: "Prefer this over plane.add_curve when describing a circle, radius, diameter, or tangent setup.",
      input_schema: {
        type: "object",
        properties: {
          id: { type: "string" },
          center_x: { type: "number" },
          center_y: { type: "number" },
          radius: { type: "number", minimum: 0.0001 },
          label: { type: "string" },
          color: { type: "string" },
          fill_color: { type: "string" },
          opacity: { type: "number", minimum: 0, maximum: 1 },
          width: { type: "number", minimum: 1, maximum: 8 },
        },
        required: ["center_x", "center_y", "radius"],
      },
      affected_anchors: ["plane.stage"],
      error_codes: ["invalid_view_capability_input"],
    },
    {
      id: "plane.add_ellipse",
      mode: "write",
      title: "Add Ellipse",
      description: "Add an ellipse using center and x/y radii.",
      input_schema: {
        type: "object",
        properties: {
          id: { type: "string" },
          center_x: { type: "number" },
          center_y: { type: "number" },
          radius_x: { type: "number", minimum: 0.0001 },
          radius_y: { type: "number", minimum: 0.0001 },
          label: { type: "string" },
          color: { type: "string" },
          fill_color: { type: "string" },
          opacity: { type: "number", minimum: 0, maximum: 1 },
          width: { type: "number", minimum: 1, maximum: 8 },
        },
        required: ["center_x", "center_y", "radius_x", "radius_y"],
      },
      affected_anchors: ["plane.stage"],
      error_codes: ["invalid_view_capability_input"],
    },
    {
      id: "plane.add_polygon",
      mode: "write",
      title: "Add Polygon",
      description: "Add a polygon from three or more ordered vertices.",
      input_schema: {
        type: "object",
        properties: {
          id: { type: "string" },
          points: {
            type: "array",
            minItems: 3,
            items: {
              type: "object",
              properties: {
                x: { type: "number" },
                y: { type: "number" },
              },
              required: ["x", "y"],
            },
          },
          label: { type: "string" },
          color: { type: "string" },
          fill_color: { type: "string" },
          opacity: { type: "number", minimum: 0, maximum: 1 },
          width: { type: "number", minimum: 1, maximum: 8 },
        },
        required: ["points"],
      },
      affected_anchors: ["plane.stage"],
      error_codes: ["invalid_view_capability_input"],
    },
    {
      id: "plane.add_arc",
      mode: "write",
      title: "Add Arc",
      description: "Add a circular arc using center, radius, and start/end degrees.",
      input_schema: {
        type: "object",
        properties: {
          id: { type: "string" },
          center_x: { type: "number" },
          center_y: { type: "number" },
          radius: { type: "number", minimum: 0.0001 },
          start_angle_deg: { type: "number" },
          end_angle_deg: { type: "number" },
          label: { type: "string" },
          color: { type: "string" },
          fill_color: { type: "string" },
          opacity: { type: "number", minimum: 0, maximum: 1 },
          width: { type: "number", minimum: 1, maximum: 8 },
        },
        required: ["center_x", "center_y", "radius", "start_angle_deg", "end_angle_deg"],
      },
      affected_anchors: ["plane.stage"],
      error_codes: ["invalid_view_capability_input"],
    },
    {
      id: "plane.add_angle_marker",
      mode: "write",
      title: "Add Angle Marker",
      description: "Mark one angle using three coordinates and a swept direction, suitable for geometry teaching.",
      assistant_hint: "Prefer this over plane.add_arc for labels such as ∠ABC, x, or 45°. Use sweep_direction to choose which side of the angle is rendered, and use marker_style=right_angle_square only when you want a 90-degree teaching marker.",
      input_schema: {
        type: "object",
        properties: {
          id: { type: "string" },
          ax: { type: "number" },
          ay: { type: "number" },
          vertex_x: { type: "number" },
          vertex_y: { type: "number" },
          bx: { type: "number" },
          by: { type: "number" },
          sweep_direction: { type: "string", enum: ["counterclockwise", "clockwise"] },
          marker_style: { type: "string", enum: ["arc", "right_angle_square"] },
          radius: { type: "number", minimum: 0.0001 },
          label: { type: "string" },
          color: { type: "string" },
          fill_color: { type: "string" },
          opacity: { type: "number", minimum: 0, maximum: 1 },
          width: { type: "number", minimum: 1, maximum: 8 },
        },
        required: ["ax", "ay", "vertex_x", "vertex_y", "bx", "by", "sweep_direction", "radius"],
      },
      affected_anchors: ["plane.stage"],
      error_codes: ["invalid_view_capability_input"],
    },
    {
      id: "plane.add_vector",
      mode: "write",
      title: "Add Vector",
      description: "Add a directed vector from start coordinate to end coordinate.",
      input_schema: {
        type: "object",
        properties: {
          id: { type: "string" },
          x1: { type: "number" },
          y1: { type: "number" },
          x2: { type: "number" },
          y2: { type: "number" },
          label: { type: "string" },
          color: { type: "string" },
          fill_color: { type: "string" },
          opacity: { type: "number", minimum: 0, maximum: 1 },
          width: { type: "number", minimum: 1, maximum: 8 },
          dashed: { type: "boolean" },
        },
        required: ["x1", "y1", "x2", "y2"],
      },
      affected_anchors: ["plane.stage"],
      error_codes: ["invalid_view_capability_input"],
    },
    {
      id: "plane.add_annotation",
      mode: "write",
      title: "Add Annotation",
      description: "Add either free text or a marker tag at one coordinate position.",
      input_schema: {
        type: "object",
        properties: {
          id: { type: "string" },
          annotation_type: { type: "string", enum: ["label", "marker"] },
          x: { type: "number" },
          y: { type: "number" },
          text: { type: "string" },
          label: { type: "string" },
          color: { type: "string" },
          size: { type: "number", minimum: 1, maximum: 12 },
        },
        required: ["x", "y"],
      },
      affected_anchors: ["plane.stage"],
    },
    {
      id: "plane.show_formula_label",
      mode: "write",
      title: "Show Formula Label",
      description: "Place a formula or geometric conclusion label directly on the stage.",
      input_schema: {
        type: "object",
        properties: {
          id: { type: "string" },
          x: { type: "number" },
          y: { type: "number" },
          text: { type: "string" },
          label: { type: "string" },
          color: { type: "string" },
          fill_color: { type: "string" },
          opacity: { type: "number", minimum: 0, maximum: 1 },
        },
        required: ["x", "y", "text"],
      },
      affected_anchors: ["plane.stage"],
      error_codes: ["invalid_view_capability_input"],
    },
    {
      id: "plane.set_label",
      mode: "write",
      title: "Set Label",
      description: "Patch the visible label and lightweight label position of one existing object.",
      assistant_hint: "Use this after drawing when you want names like O, OA, or Triangle ABC without recreating the object.",
      input_schema: {
        type: "object",
        properties: {
          target_id: { type: "string" },
          label: { type: "string" },
          label_anchor: {
            type: "string",
            enum: ["auto", "center", "midpoint", "start", "end", "top", "right", "bottom", "left"],
          },
          label_offset_dx: { type: "number" },
          label_offset_dy: { type: "number" },
        },
        required: ["target_id"],
      },
      affected_anchors: ["plane.stage"],
      error_codes: ["invalid_view_capability_input"],
    },
    {
      id: "plane.highlight",
      mode: "write",
      title: "Highlight Objects",
      description: "Highlight one or more existing object ids to focus the explanation.",
      assistant_hint: "Prefer highlighting already-created ids such as a point, line, curve, or moving object before calling guide.narrate.",
      input_schema: {
        type: "object",
        properties: {
          id: { type: "string" },
          target_ids: {
            type: "array",
            minItems: 1,
            items: { type: "string" },
          },
          label: { type: "string" },
          color: { type: "string" },
        },
        required: ["target_ids"],
      },
      affected_anchors: ["plane.stage"],
      error_codes: ["invalid_view_capability_input"],
    },
    {
      id: "plane.clear_highlight",
      mode: "write",
      title: "Clear Highlight",
      description: "Remove all current highlights from the plane.",
      input_schema: {
        type: "object",
        properties: {},
      },
      affected_anchors: ["plane.stage"],
    },
    {
      id: "plane.set_style",
      mode: "write",
      title: "Set Style",
      description: "Apply a lightweight visual patch to one or more existing object ids.",
      assistant_hint: "Use this to emphasize radius, edge, arc, or formula labels without recreating the object.",
      input_schema: {
        type: "object",
        properties: {
          target_ids: {
            type: "array",
            minItems: 1,
            items: { type: "string" },
          },
          color: { type: "string" },
          fill_color: { type: "string" },
          width: { type: "number", minimum: 1, maximum: 8 },
          dashed: { type: "boolean" },
          opacity: { type: "number", minimum: 0, maximum: 1 },
          size: { type: "number", minimum: 1, maximum: 18 },
        },
        required: ["target_ids"],
      },
      affected_anchors: ["plane.stage"],
      error_codes: ["invalid_view_capability_input"],
    },
    {
      id: "plane.focus_region",
      mode: "write",
      title: "Focus Region",
      description: "Zoom viewport to a local region using explicit bounds or center plus span.",
      assistant_hint: "Prefer this before guide.narrate when explaining one vertex, one radius, or a local angle.",
      input_schema: {
        type: "object",
        properties: {
          x_min: { type: "number" },
          x_max: { type: "number" },
          y_min: { type: "number" },
          y_max: { type: "number" },
          center_x: { type: "number" },
          center_y: { type: "number" },
          x_span: { type: "number", minimum: 0.0001 },
          y_span: { type: "number", minimum: 0.0001 },
        },
      },
      affected_anchors: ["plane.stage"],
      error_codes: ["invalid_view_capability_input"],
    },
    {
      id: "plane.add_object",
      mode: "write",
      title: "Add Object",
      description: "Add or replace one simple moving object represented as a circle or rectangle.",
      input_schema: {
        type: "object",
        properties: {
          id: { type: "string" },
          shape: { type: "string", enum: ["circle", "rect"] },
          x: { type: "number" },
          y: { type: "number" },
          label: { type: "string" },
          color: { type: "string" },
          size: { type: "number", minimum: 2, maximum: 18 },
        },
      },
      affected_anchors: ["plane.stage"],
    },
    {
      id: "plane.animate_object",
      mode: "write",
      title: "Animate Object",
      description: "Move one existing object to a target coordinate over a duration.",
      assistant_hint: "Use this after plane.add_object. If later steps need to wait for the motion, match assistant.plane.animation_completed.",
      input_schema: {
        type: "object",
        properties: {
          object_id: { type: "string" },
          to_x: { type: "number" },
          to_y: { type: "number" },
          duration_ms: { type: "number", minimum: 0, maximum: 30000 },
        },
        required: ["object_id", "to_x", "to_y"],
      },
      affected_anchors: ["plane.stage"],
      error_codes: ["invalid_view_capability_input", "plane_object_not_found"],
    },
    {
      id: "plane.get_scene_state",
      mode: "read",
      title: "Get Scene State",
      description: "Read viewport, object counts, highlight counts, and animation summary.",
      input_schema: {
        type: "object",
        properties: {},
      },
      affected_anchors: ["plane.header", "plane.stage"],
    },
  ],
  interaction_hints: {
    interaction_intent: "Best for AI-led coordinate explanations, geometry walkthroughs, angle marking, solution-step demos, and motion scenes that need drawing, naming objects, highlighting, formula labels, and simple animation on one immersive stage.",
    recommended_mode: "session_start",
    decision_rule: "Open the coordinate plane first, then describe it. Reads can call plane.get_scene_state directly, but any teaching flow with viewport setup, drawing, angle markers, formula labels, motion, or focus changes should usually use session.start so guide.narrate stays aligned with plane capabilities.",
    key_events: [
      {
        type: "assistant.plane.animation_completed",
        description: "Emitted when one animated object finishes moving to its target coordinate.",
        match_fields: ["object_id", "view_id"],
      },
    ],
    examples: coordinatePlaneMainExamples,
  },
  persistence: coordinatePlaneMainPersistence,
  normalizeResource: validateCoordinatePlaneResource,
  open: openCoordinatePlaneMainView,
  invokeCapability: invokeCoordinatePlaneMainCapability,
  getStateSummary: buildCoordinatePlaneMainStateSummary,
});
