#!/usr/bin/env python3
"""
Auto bump plugin versions (patch) based on immutable conflict report.
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from pathlib import Path


SEMVER_RE = re.compile(r"^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$")
PYPROJECT_VERSION_RE = re.compile(r'(?m)^version\s*=\s*"([^"]+)"\s*$')
SHARED_RULES_PLUGIN_ID = "__shared_opencode_rules__"


@dataclass
class BumpResult:
    plugin_id: str
    old_version: str
    new_version: str
    touched_paths: tuple[Path, ...]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Bump plugin patch versions using conflicts JSON report.")
    parser.add_argument(
        "--conflicts-json",
        required=True,
        help="Path to conflicts JSON generated by package_plugins.py --conflicts-json",
    )
    parser.add_argument(
        "--plugins-root",
        default="official-plugins",
        help="Directory containing plugin folders",
    )
    parser.add_argument(
        "--shared-rules-root",
        default=".opencode",
        help="Directory containing shared OpenCode rules manifest.json",
    )
    return parser.parse_args()


def _parse_semver(version: str) -> tuple[int, int, int]:
    match = SEMVER_RE.match(version.strip())
    if not match:
        raise RuntimeError(f"Unsupported version format (expected x.y.z): {version}")
    return int(match.group(1)), int(match.group(2)), int(match.group(3))


def _bump_patch(version: str) -> str:
    major, minor, patch = _parse_semver(version)
    return f"{major}.{minor}.{patch + 1}"


def _read_json(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as f:
        payload = json.load(f)
    if not isinstance(payload, dict):
        raise RuntimeError(f"Expected JSON object: {path}")
    return payload


def _collect_plugin_dirs(plugins_root: Path) -> dict[str, Path]:
    plugin_dirs: dict[str, Path] = {}
    for child in sorted(plugins_root.iterdir()):
        if not child.is_dir():
            continue
        manifest_path = child / "manifest.json"
        if not manifest_path.exists():
            continue
        manifest = _read_json(manifest_path)
        plugin_id = str(manifest.get("id") or "").strip()
        if not plugin_id:
            raise RuntimeError(f"Missing plugin id in {manifest_path}")
        if plugin_id in plugin_dirs:
            raise RuntimeError(f"Duplicate plugin id detected: {plugin_id}")
        plugin_dirs[plugin_id] = child
    return plugin_dirs


def _update_manifest_version(manifest_path: Path, old_version: str, new_version: str) -> None:
    manifest = _read_json(manifest_path)
    current = str(manifest.get("version") or "")
    if current != old_version:
        raise RuntimeError(f"Manifest version mismatch in {manifest_path}: expected {old_version}, got {current}")
    manifest["version"] = new_version
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def _update_pyproject_version(pyproject_path: Path, old_version: str, new_version: str) -> None:
    content = pyproject_path.read_text(encoding="utf-8")
    match = PYPROJECT_VERSION_RE.search(content)
    if not match:
        raise RuntimeError(f"Cannot find version field in {pyproject_path}")
    current = match.group(1).strip()
    if current != old_version:
        raise RuntimeError(f"Pyproject version mismatch in {pyproject_path}: expected {old_version}, got {current}")
    updated = PYPROJECT_VERSION_RE.sub(f'version = "{new_version}"', content, count=1)
    pyproject_path.write_text(updated, encoding="utf-8")


def _update_shared_rules_manifest(manifest_path: Path, old_version: str, new_version: str) -> None:
    manifest = _read_json(manifest_path)
    current = str(manifest.get("version") or "").strip()
    if current != old_version:
        raise RuntimeError(f"Shared rules version mismatch in {manifest_path}: expected {old_version}, got {current}")

    manifest["version"] = new_version
    current_package_name = str(manifest.get("package_name") or "").strip()
    default_old_name = f"opencode-rules-{old_version}.zip"
    default_new_name = f"opencode-rules-{new_version}.zip"
    if not current_package_name or current_package_name == default_old_name:
        manifest["package_name"] = default_new_name
    elif old_version in current_package_name:
        manifest["package_name"] = current_package_name.replace(old_version, new_version, 1)

    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def _load_conflicts(conflicts_json: Path) -> dict[str, str]:
    payload = _read_json(conflicts_json)
    entries = payload.get("conflicts")
    if not isinstance(entries, list):
        raise RuntimeError(f"Invalid conflicts payload in {conflicts_json}: missing 'conflicts' list")
    by_plugin: dict[str, str] = {}
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        plugin_id = str(entry.get("plugin_id") or "").strip()
        version = str(entry.get("version") or "").strip()
        if not plugin_id or not version:
            continue
        prev = by_plugin.get(plugin_id)
        if prev is not None and prev != version:
            raise RuntimeError(
                f"Conflicting versions in report for plugin {plugin_id}: {prev} vs {version}"
            )
        by_plugin[plugin_id] = version
    if not by_plugin and entries:
        raise RuntimeError(f"No valid conflict entries found in {conflicts_json}")
    return by_plugin


def main() -> int:
    args = parse_args()
    repo_root = Path(__file__).resolve().parents[1]
    plugins_root = (repo_root / args.plugins_root).resolve()
    shared_rules_root = (repo_root / args.shared_rules_root).resolve()
    conflicts_json = Path(args.conflicts_json).resolve()

    if not plugins_root.exists():
        raise FileNotFoundError(f"plugins root not found: {plugins_root}")
    if not conflicts_json.exists():
        raise FileNotFoundError(f"conflicts json not found: {conflicts_json}")

    conflict_versions = _load_conflicts(conflicts_json)
    if not conflict_versions:
        print("no conflicts found, nothing to bump")
        return 0
    print(f"conflict plugins to process: {len(conflict_versions)}")

    plugin_dirs = _collect_plugin_dirs(plugins_root)
    results: list[BumpResult] = []

    for plugin_id in sorted(conflict_versions):
        old_version = conflict_versions[plugin_id]
        new_version = _bump_patch(old_version)

        if plugin_id == SHARED_RULES_PLUGIN_ID:
            manifest_path = shared_rules_root / "manifest.json"
            if not manifest_path.exists():
                raise RuntimeError(f"Shared rules manifest not found: {manifest_path}")
            _update_shared_rules_manifest(manifest_path, old_version, new_version)
            results.append(
                BumpResult(
                    plugin_id=plugin_id,
                    old_version=old_version,
                    new_version=new_version,
                    touched_paths=(manifest_path,),
                )
            )
            continue

        plugin_dir = plugin_dirs.get(plugin_id)
        if plugin_dir is None:
            raise RuntimeError(f"Plugin id from conflicts not found under plugins root: {plugin_id}")

        manifest_path = plugin_dir / "manifest.json"
        pyproject_path = plugin_dir / "pyproject.toml"
        resolved_pyproject: Path | None = pyproject_path if pyproject_path.exists() else None

        _update_manifest_version(manifest_path, old_version, new_version)
        touched_paths = [manifest_path]
        if resolved_pyproject is not None:
            _update_pyproject_version(resolved_pyproject, old_version, new_version)
            touched_paths.append(resolved_pyproject)

        results.append(
            BumpResult(
                plugin_id=plugin_id,
                old_version=old_version,
                new_version=new_version,
                touched_paths=tuple(touched_paths),
            )
        )

    for item in results:
        print(f"bumped {item.plugin_id}: {item.old_version} -> {item.new_version}")
    touched_files: set[Path] = set()
    pyproject_updates = 0
    shared_rules_updates = 0
    for item in results:
        if item.plugin_id == SHARED_RULES_PLUGIN_ID:
            shared_rules_updates += 1
        for path in item.touched_paths:
            touched_files.add(path)
            if path.name == "pyproject.toml":
                pyproject_updates += 1
    print(
        "bump summary: "
        f"plugins={len(results)}, manifest_updates={len(results)}, "
        f"pyproject_updates={pyproject_updates}, shared_rules_updates={shared_rules_updates}, "
        f"touched_files={len(touched_files)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
