export const BRIDGE_MESSAGE_TYPE = {
  REQUEST: 'bridge.request',
  RESULT: 'bridge.result',
  EVENT: 'bridge.event'
} as const

export const BRIDGE_EVENT = {
  CONTEXT_PUSH: 'context_push',
  TTS_SPEAK_ACCEPTED: 'tts_speak_accepted',
  TTS_STOPPED: 'tts_stopped'
} as const

export const IFRAME_UI_AGENT_MESSAGE = {
  SNAPSHOT_REQUEST: 'DAWNCHAT_UI_AGENT_SNAPSHOT_REQUEST',
  QUERY_REQUEST: 'DAWNCHAT_UI_AGENT_QUERY_REQUEST',
  ACTION_REQUEST: 'DAWNCHAT_UI_AGENT_ACTION_REQUEST',
  SCROLL_REQUEST: 'DAWNCHAT_UI_AGENT_SCROLL_REQUEST',
  CAPABILITIES_LIST_REQUEST: 'DAWNCHAT_UI_AGENT_CAPABILITIES_LIST_REQUEST',
  CAPABILITY_INVOKE_REQUEST: 'DAWNCHAT_UI_AGENT_CAPABILITY_INVOKE_REQUEST',
  RUNTIME_REFRESH_REQUEST: 'DAWNCHAT_UI_AGENT_RUNTIME_REFRESH_REQUEST',
  SNAPSHOT_RESPONSE: 'DAWNCHAT_UI_AGENT_SNAPSHOT_RESPONSE',
  QUERY_RESPONSE: 'DAWNCHAT_UI_AGENT_QUERY_RESPONSE',
  ACTION_RESULT: 'DAWNCHAT_UI_AGENT_ACTION_RESULT',
  SCROLL_RESULT: 'DAWNCHAT_UI_AGENT_SCROLL_RESULT',
  CAPABILITIES_LIST_RESPONSE: 'DAWNCHAT_UI_AGENT_CAPABILITIES_LIST_RESPONSE',
  CAPABILITY_INVOKE_RESULT: 'DAWNCHAT_UI_AGENT_CAPABILITY_INVOKE_RESULT',
  RUNTIME_REFRESH_RESULT: 'DAWNCHAT_UI_AGENT_RUNTIME_REFRESH_RESULT',
  HOST_INVOKE_REQUEST: 'DAWNCHAT_HOST_INVOKE_REQUEST',
  HOST_INVOKE_RESULT: 'DAWNCHAT_HOST_INVOKE_RESULT',
  ASSISTANT_RUNTIME_EVENT: 'DAWNCHAT_ASSISTANT_RUNTIME_EVENT'
} as const

export const UI_AGENT_RESPONSE_TYPES = new Set<string>([
  IFRAME_UI_AGENT_MESSAGE.SNAPSHOT_RESPONSE,
  IFRAME_UI_AGENT_MESSAGE.QUERY_RESPONSE,
  IFRAME_UI_AGENT_MESSAGE.ACTION_RESULT,
  IFRAME_UI_AGENT_MESSAGE.SCROLL_RESULT,
  IFRAME_UI_AGENT_MESSAGE.CAPABILITIES_LIST_RESPONSE,
  IFRAME_UI_AGENT_MESSAGE.CAPABILITY_INVOKE_RESULT,
  IFRAME_UI_AGENT_MESSAGE.RUNTIME_REFRESH_RESULT
])
